### PR TITLE
Fix scrolling, update script according to facebook changes, save join…

### PR DESCRIPTION
**Pull request by lez**
… date, version bump to 0.2

Hi, Mark!
I hope you're somewhat maintaining the script - this is a small update to make it work with current facebook, large groups. Also I added the feature to save group join date of the user.

Please review/test/merge the code, or else, get back with your intentions with the software. I agree that all my code can be distributed under the project MIT license.

Here comes the original commit message body:
```
Scrolling is as fast as it can get.
The script doesn't unexpectedly finish in the middle.
Facebook classes have probably been updated, this version uses the new classes.
TODO when a user was added by somebody else, it should be saved in csv 'joined' field.
```

### CODE REVIEW

**Comment by markmetcalfe** [comment]
Hi Laszlo, thanks for your contribution! I've taken a brief look at it, and have found it not to work on the group I originally made the script for which is odd. I'll take a deeper look at what is going on tomorrow and see if there is a solution (plus I'll push up some minor changes too)

**Comment by lez** [comment]
Ok, I think I found an error in that, too. The console says (in another group):
`ErrorUtils caught an error: "recent_members is null".` - I'll fix it.

**Comment by lez** [comment]
Fixed the issue I've met. (See the FIXUP commit above) The problem was that smaller groups doesn't have this section "Recently joined" where members are enumerated in the reverse order they have joined.

Tried in a few groups, all of them seem to be working now.

In case of merging: remember to squash the fixup commits into the first using `git rebase -i --autosquash <first-commit-id>^` - or I can do it.

**Comment by markmetcalfe** [comment]
Sorry it took me so long to get to this - getting ready for Christmas and things are busy! Have merged this manually now - thanks so much @lez !

**Pull request closed without merging**
